name = "flareact-with-typescript"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
